# Generated by Django 4.1.7 on 2023-05-01 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribers',
            new_name='Subscriber',
        ),
        migrations.CreateModel(
            name='SentEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_successful', models.BooleanField(default=False)),
                ('is_opened', models.BooleanField(default=False)),
                ('tracking_id', models.UUIDField(unique=True)),
                ('receipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.subscriber')),
            ],
        ),
    ]
