# Generated by Django 4.1.7 on 2023-05-01 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_subscribers_subscriber_sentemail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentemail',
            old_name='receipient',
            new_name='recipient',
        ),
    ]
